/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cnksi_core_utils_EncryptUtils */

#ifndef _Included_com_cnksi_core_utils_EncryptUtils
#define _Included_com_cnksi_core_utils_EncryptUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cnksi_core_utils_EncryptUtils
 * Method:    isEquals
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cnksi_core_utils_EncryptUtils_isEquals
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
